on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    - name: Call Github API
      container: appropriate/curl
      steps:
      - name: say hi
        run: |
          echo HELLO!
